### ISSUE TITLE
help~~dzr_audio is what?

### ISSUE THREAD

**Issue by seth-64** [albincorreya/ChromaFeatures_CoverID#1]
"from dzr_audio.signals import Signal"
i can't find anywhere

**Comment by seth-64** [comment]
it may be that   "deezer-chromaprint" ?

**Comment by albincorreya** [comment]
Thanks for pointing it out ! 
"dzr_audio" was a internal package to handle audio files from a audio database.
I had removed it with a regular audio file loader where you can specify audio file path as the argument.
Check the latest commits. Let me know if there is anything else !

Cheers
